set search_path = tariel;

drop table if exists api_requests;
create table if not exists api_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    url VARCHAR(500),
    status_code smallint,
    issued TIMESTAMP NOT NULL DEFAULT now(),
    PRIMARY KEY(id));